name: Test Runner
on: [push]
env:
 CLIENT_URL: http://localhost:3000
 SERVER_URL: http://localhost:5000
 DATABASE_URL: postgres://testdbusr:testpassword@postgres:5432/test
 SALT_ROUNDS: 10
 TOKEN_SECRET: testrunner
 TOKEN_EXPIRATION: 1d
 STRIPE_API_KEY: sktest_573457348
 STRIPE_ENDPOINT_SECRET: sktest_2839710234723
 STRIPE_CURRENCY: GBP
 STRIPE_WEBHOOK_SECRET_ORDER: sktest_239048230984
jobs:
  perform-test-run:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testdbusr
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Connect to PostgreSQL, create the db,tables and data
        run: node setup_db.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: testdbusr
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: test
      - name: Run tests
        run: npm test
